name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn run cy:run
          wait-on: http://localhost:4200
