name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0

      - name: Run Unit tests
        with:
          build: yarn run test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn run cy:run
          wait-on: http://localhost:4200
